### ISSUE TITLE
bs4 couldn't find a tree builder

### ISSUE THREAD

**Issue by krischan941** [phoelix/facefetch#1]
Got this message by starting the script:

> 
> python3 ffetch . -n 20
> Collecting img urls...
> Traceback (most recent call last):
>   File "ffetch", line 217, in <module>
>     main()
>   File "ffetch", line 87, in main
>     urls = fetcher.collect_urls(query)
>   File "ffetch", line 140, in collect_urls
>     soup = BeautifulSoup(html, 'lxml')
>   File "/usr/lib/python3.5/site-packages/bs4/__init__.py", line 165, in __init__
>     % ",".join(features))
> bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by fcornelius** [comment]
"Do you need to install a parser library?" suggests you have no parser library like lxml installed on your system. Apt has a package called python3-lxml, or you can install it via pip with sudo pip install lxml

**Comment by krischan941** [comment]
Thanks! It works flawlessly
